# Generated by Django 5.1.7 on 2025-04-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_userdetail_qualification_user_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='bio',
            field=models.TextField(default='Novice Django Developer but building unique portfolio'),
        ),
    ]
