# Generated by Django 5.2.1 on 2025-05-21 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('high_contrast', 'High Contrast'), ('custom', 'Custom')], default='light', max_length=20)),
                ('primary_color', models.CharField(default='#007bff', max_length=20)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20)),
                ('success_color', models.CharField(default='#28a745', max_length=20)),
                ('danger_color', models.CharField(default='#dc3545', max_length=20)),
                ('warning_color', models.CharField(default='#ffc107', max_length=20)),
                ('info_color', models.CharField(default='#17a2b8', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#212529', max_length=20)),
                ('font_family', models.CharField(choices=[('system', 'System Default'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('open_sans', 'Open Sans'), ('montserrat', 'Montserrat')], default='system', max_length=20)),
                ('base_font_size', models.CharField(default='16px', max_length=10)),
                ('heading_font_family', models.CharField(choices=[('system', 'System Default'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('open_sans', 'Open Sans'), ('montserrat', 'Montserrat')], default='system', max_length=20)),
                ('border_radius', models.CharField(default='0.25rem', max_length=10)),
                ('spacing_unit', models.CharField(default='1rem', max_length=10)),
                ('container_max_width', models.CharField(default='1140px', max_length=10)),
                ('enable_animations', models.BooleanField(default=True)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('high_contrast_mode', models.BooleanField(default=False)),
                ('font_scaling', models.FloatField(default=1.0)),
                ('increase_target_size', models.BooleanField(default=False)),
                ('custom_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(help_text='CSS selector for the element', max_length=255)),
                ('element_type', models.CharField(choices=[('global', 'Global Element'), ('navigation', 'Navigation Element'), ('course', 'Course Element'), ('quiz', 'Quiz Element'), ('content', 'Content Element'), ('form', 'Form Element'), ('custom', 'Custom Element')], default='custom', max_length=20)),
                ('aria_label', models.CharField(blank=True, max_length=255)),
                ('aria_role', models.CharField(blank=True, max_length=50)),
                ('aria_description', models.TextField(blank=True)),
                ('additional_attributes', models.JSONField(blank=True, default=dict)),
                ('is_skip_target', models.BooleanField(default=False)),
                ('skip_target_name', models.CharField(blank=True, max_length=50)),
                ('tab_index', models.IntegerField(blank=True, null=True)),
                ('keyboard_shortcut', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes for developers and content editors')),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accessibility Element',
                'verbose_name_plural': 'Accessibility Elements',
                'unique_together': {('selector', 'element_type')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('system', 'Use System Preference'), ('light', 'Light'), ('dark', 'Dark'), ('high_contrast', 'High Contrast')], default='system', max_length=20)),
                ('motion_preference', models.CharField(choices=[('system', 'Use System Preference'), ('full', 'Full Animations'), ('reduced', 'Reduced Animations'), ('none', 'No Animations')], default='system', max_length=20)),
                ('text_size', models.CharField(choices=[('system', 'Use System Preference'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='system', max_length=20)),
                ('use_custom_colors', models.BooleanField(default=False)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('high_contrast', models.BooleanField(default=False)),
                ('increase_text_spacing', models.BooleanField(default=False)),
                ('dyslexia_friendly_font', models.BooleanField(default=False)),
                ('screen_reader_optimization', models.BooleanField(default=False)),
                ('keyboard_navigation_optimization', models.BooleanField(default=False)),
                ('simplified_navigation', models.BooleanField(default=False)),
                ('show_content_outlines', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
