# Generated by Django 5.2 on 2025-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_content_estimated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_students",
            field=models.PositiveIntegerField(
                default=100, help_text="Maximum number of students allowed to enroll"
            ),
        ),
    ]
