# Generated by Django 5.2 on 2025-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_max_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_prerequisite",
            field=models.BooleanField(
                default=False,
                help_text="Whether this quiz is a prerequisite for the module",
            ),
        ),
    ]
