# Generated by Django 5.2 on 2025-05-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("publish_course", "Can publish course"),
                    ("archive_course", "Can archive course"),
                ],
            },
        ),
    ]
