# Generated by Django 5.2 on 2025-04-30 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_courseenrollment_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Hex color code (e.g., '#3B82F6')",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="icon",
            field=models.CharField(
                default="academic-cap",
                help_text="Heroicon name (e.g., 'academic-cap', 'code', 'beaker')",
                max_length=50,
            ),
        ),
    ]
