# Generated by Django 5.2 on 2025-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="estimated_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated time in minutes", null=True
            ),
        ),
    ]
