# Generated by Django 5.2 on 2025-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_question_choice_quiz_question_quiz_quizattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_pre_check",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is a pre-requisite survey with no right/wrong answers",
            ),
        ),
    ]
