# Generated by Django 5.2 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="time_spent",
            field=models.IntegerField(
                default=0, help_text="Time spent on this question in seconds"
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True, help_text="Last activity timestamp"
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="time_spent",
            field=models.IntegerField(
                default=0, help_text="Total time spent in seconds"
            ),
        ),
    ]
