# Generated by Django 5.2.1 on 2025-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_end_date_course_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completion_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Criteria for marking as complete (e.g. {"video_watched": true, "quiz_completed": true})'),
        ),
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, help_text='Module content in markdown format'),
        ),
        migrations.AddField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Estimated time to complete in minutes'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Is this module required for course completion'),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='courses.module'),
        ),
    ]
