# Generated by Django 5.2.1 on 2025-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_completion_criteria_module_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('self_paced', 'Self-Paced'), ('intensive', 'Intensive')], default='standard', max_length=20),
        ),
    ]
