# Generated by Django 5.2.1 on 2025-05-20 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_choice_image_choice_image_alt_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, help_text='Optional access code required to take this quiz', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_time_extension',
            field=models.BooleanField(default=False, help_text='Whether instructors can grant time extensions'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When this quiz becomes available', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='When this quiz is no longer available', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=2, help_text='Grace period in minutes after time limit expires'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_choices',
            field=models.BooleanField(default=False, help_text='Randomize choice order for multiple choice questions'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_feedback_after',
            field=models.CharField(choices=[('each_question', 'After each question'), ('completion', 'After completion'), ('due_date', 'After due date'), ('never', 'Never')], default='completion', help_text='When to show feedback to students', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='extended_by',
            field=models.ForeignKey(blank=True, help_text='Instructor who granted the time extension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='extension_reason',
            field=models.TextField(blank=True, help_text='Reason for granting time extension'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last recorded activity in this attempt', null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_extension_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Additional time granted by instructor'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_warning_sent',
            field=models.BooleanField(default=False, help_text='Whether a time warning has been sent'),
        ),
    ]
