# Generated by Django 5.2.1 on 2025-05-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_quiz_access_code_quiz_allow_time_extension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_passing', models.BooleanField(default=True, help_text='Whether the prerequisite needs to be passed or just attempted')),
                ('bypass_for_instructors', models.BooleanField(default=True, help_text='Whether instructors can bypass this prerequisite')),
                ('prerequisite_quiz', models.ForeignKey(help_text='The quiz that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.quiz')),
                ('quiz', models.ForeignKey(help_text='The quiz that requires completion of prerequisites', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Prerequisite',
                'verbose_name_plural': 'Quiz Prerequisites',
                'unique_together': {('quiz', 'prerequisite_quiz')},
            },
        ),
    ]
