# Generated by Django 5.2.1 on 2025-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_quizprerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_neutral',
            field=models.BooleanField(default=False, help_text='If true, this choice neither adds nor subtracts points'),
        ),
        migrations.AddField(
            model_name='choice',
            name='points_value',
            field=models.IntegerField(default=0, help_text='Points to award for this choice (negative for penalties)'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='minimum_score',
            field=models.IntegerField(default=0, help_text='Minimum score even with negative points'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='use_partial_credit',
            field=models.BooleanField(default=False, help_text='Use partial credit scoring'),
        ),
    ]
