# Generated by Django 5.2.1 on 2025-05-20 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_choice_is_neutral_choice_points_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('incorrect_attempts', models.PositiveIntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(default=0.0)),
                ('difficulty_index', models.FloatField(default=0.0, help_text='Percentage of students who answered correctly (0.0-1.0)')),
                ('discrimination_index', models.FloatField(default=0.0, help_text='How well the question differentiates high and low performers (-1.0 to 1.0)')),
                ('choice_distribution', models.JSONField(blank=True, default=dict)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.question')),
            ],
            options={
                'verbose_name': 'Question Analytics',
                'verbose_name_plural': 'Question Analytics',
            },
        ),
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('completed_attempts', models.PositiveIntegerField(default=0)),
                ('passing_attempts', models.PositiveIntegerField(default=0)),
                ('avg_completion_time', models.FloatField(default=0.0, help_text='Average completion time in seconds')),
                ('avg_score', models.FloatField(default=0.0, help_text='Average score (percentage)')),
                ('lowest_scoring_questions', models.JSONField(blank=True, default=list)),
                ('highest_scoring_questions', models.JSONField(blank=True, default=list)),
                ('score_distribution', models.JSONField(blank=True, default=dict)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Analytics',
                'verbose_name_plural': 'Quiz Analytics',
            },
        ),
    ]
