# Generated by Django 5.2.1 on 2025-05-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_questionanalytics_quizanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='annotated_by',
            field=models.ForeignKey(blank=True, help_text='Instructor who added the annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='annotation_added_at',
            field=models.DateTimeField(blank=True, help_text='When the annotation was added', null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='instructor_annotation',
            field=models.TextField(blank=True, help_text='Instructor annotation for any question type'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='conditional_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='Feedback shown based on score ranges (e.g., {"0-59": "...", "60-79": "...", "80-100": "..."})'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='feedback_delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Delay in minutes before feedback is shown (0 for immediate)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='general_feedback',
            field=models.TextField(blank=True, help_text='General feedback shown to all students after quiz completion'),
        ),
    ]
