# Generated by Django 5.2.1 on 2025-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_multiplechoicequestion_normalization_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='analytics_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='engagement_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
