# Generated by Django 5.2.1 on 2025-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_analytics_enabled_course_analytics_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qr_enabled',
            field=models.BooleanField(default=False, help_text='Enable QR code access for this course'),
        ),
        migrations.AddField(
            model_name='module',
            name='qr_access',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('public', 'Public Access'), ('enrolled', 'Enrolled Students Only'), ('instructor', 'Instructors Only')], default='disabled', help_text='QR code access level for this module', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='qr_tracking',
            field=models.BooleanField(default=False, help_text='Track QR code scans for quiz access'),
        ),
    ]
