# Generated by Django 5.2.1 on 2025-05-20 18:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_questionanalytics_quizanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_signature', models.CharField(max_length=255, unique=True)),
                ('path_description', models.TextField()),
                ('path_modules', models.JSONField(default=list)),
                ('user_count', models.IntegerField(default=0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Learning Path Analytics',
            },
        ),
        migrations.CreateModel(
            name='CourseAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.IntegerField(default=0)),
                ('active_learners', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('engagement_trend', models.JSONField(blank=True, default=dict)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Course Analytics Summaries',
            },
        ),
        migrations.CreateModel(
            name='ModuleEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(default=datetime.timedelta)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('interaction_data', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_engagements', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'user'], name='analytics_m_module__c7bbf7_idx'), models.Index(fields=['user', 'last_viewed'], name='analytics_m_user_id_8f2f44_idx')],
                'unique_together': {('module', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'), models.Index(fields=['activity_type', 'timestamp'], name='analytics_u_activit_f59ac3_idx')],
            },
        ),
    ]
