# Generated by Django 5.2.1 on 2025-05-20 22:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_learneranalytics'),
        ('courses', '0016_course_analytics_enabled_course_analytics_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learneranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('concurrent_sessions', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('database_connections', models.PositiveIntegerField(default=0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('error_counts', models.JSONField(blank=True, default=dict)),
                ('error_trends', models.JSONField(blank=True, default=dict)),
                ('critical_errors', models.JSONField(blank=True, default=list)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('session_distribution', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['timestamp'], name='analytics_s_timesta_18d793_idx'), models.Index(fields=['active_users'], name='analytics_s_active__f176ae_idx'), models.Index(fields=['error_rate'], name='analytics_s_error_r_9b5105_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('active_enrollments', models.PositiveIntegerField(default=0)),
                ('new_enrollments', models.PositiveIntegerField(default=0)),
                ('enrollment_trend', models.JSONField(blank=True, default=dict)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('module_completion_rates', models.JSONField(blank=True, default=dict)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('average_score', models.FloatField(default=0.0)),
                ('score_distribution', models.JSONField(blank=True, default=dict)),
                ('module_performance', models.JSONField(blank=True, default=dict)),
                ('average_time_per_module', models.DurationField(blank=True, null=True)),
                ('total_learning_time', models.DurationField(default=datetime.timedelta)),
                ('time_distribution', models.JSONField(blank=True, default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('interaction_rates', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_analytics', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Analytics',
                'verbose_name_plural': 'Course Analytics',
                'indexes': [models.Index(fields=['course', 'last_updated'], name='analytics_c_course__58e26a_idx'), models.Index(fields=['completion_rate'], name='analytics_c_complet_48732e_idx'), models.Index(fields=['engagement_score'], name='analytics_c_engagem_398cf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_difficulty', models.JSONField(blank=True, default=dict)),
                ('question_discrimination', models.JSONField(blank=True, default=dict)),
                ('question_statistics', models.JSONField(blank=True, default=dict)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('unique_attempters', models.PositiveIntegerField(default=0)),
                ('average_attempts', models.FloatField(default=0.0)),
                ('attempt_distribution', models.JSONField(blank=True, default=dict)),
                ('average_score', models.FloatField(default=0.0)),
                ('score_distribution', models.JSONField(blank=True, default=dict)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('time_distribution', models.JSONField(blank=True, default=dict)),
                ('time_by_question', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_analytics', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Analytics',
                'verbose_name_plural': 'Quiz Analytics',
                'indexes': [models.Index(fields=['quiz', 'last_updated'], name='analytics_q_quiz_id_3c3f49_idx'), models.Index(fields=['average_score'], name='analytics_q_average_54a6be_idx'), models.Index(fields=['pass_rate'], name='analytics_q_pass_ra_58431d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_enrolled', models.PositiveIntegerField(default=0)),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('current_courses', models.JSONField(blank=True, default=list)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('activity_heatmap', models.JSONField(blank=True, default=dict)),
                ('average_score', models.FloatField(default=0.0)),
                ('quiz_completion_rate', models.FloatField(default=0.0)),
                ('module_completion_rate', models.FloatField(default=0.0)),
                ('performance_by_category', models.JSONField(blank=True, default=dict)),
                ('overall_engagement', models.FloatField(default=0.0)),
                ('course_engagement', models.JSONField(blank=True, default=dict)),
                ('interaction_frequency', models.JSONField(blank=True, default=dict)),
                ('preferred_learning_times', models.JSONField(blank=True, default=dict)),
                ('study_duration_patterns', models.JSONField(blank=True, default=dict)),
                ('content_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'indexes': [models.Index(fields=['user', 'last_active'], name='analytics_u_user_id_06ed23_idx'), models.Index(fields=['overall_engagement'], name='analytics_u_overall_ca3a4a_idx'), models.Index(fields=['completion_rate'], name='analytics_u_complet_25fe9a_idx')],
            },
        ),
    ]
