# Generated by Django 5.2 on 2025-05-03 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_answer_last_modified_answer_time_spent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorContextItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("module", "Module"),
                            ("content", "Content"),
                            ("custom", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "content_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("relevance_score", models.FloatField(default=1.0)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-relevance_score"],
            },
        ),
        migrations.CreateModel(
            name="TutorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("module", "Module"),
                            ("content", "Content"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("llm_model", models.CharField(default="default", max_length=50)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutor_sessions",
                        to="courses.content",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutor_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutor_sessions",
                        to="courses.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "relevant_context_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="used_in_messages",
                        to="ai_tutor.tutorcontextitem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_tutor.tutorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="tutorcontextitem",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_items",
                to="ai_tutor.tutorsession",
            ),
        ),
        migrations.CreateModel(
            name="ContentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_vector", models.TextField()),
                ("chunk_text", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="courses.content",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content"], name="ai_tutor_co_content_8a45b8_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="ai_tutor_co_updated_8cbf86_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tutorsession",
            index=models.Index(
                fields=["user", "created_at"], name="ai_tutor_tu_user_id_45e272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorsession",
            index=models.Index(
                fields=["course", "session_type"], name="ai_tutor_tu_course__9e0333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutormessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_tutor_tu_session_94de0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutormessage",
            index=models.Index(
                fields=["message_type"], name="ai_tutor_tu_message_4559e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorcontextitem",
            index=models.Index(
                fields=["session", "order"], name="ai_tutor_tu_session_aa0ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorcontextitem",
            index=models.Index(
                fields=["context_type", "content_object_id"],
                name="ai_tutor_tu_context_95aba0_idx",
            ),
        ),
    ]
