[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn learnmore_plus.wsgi:application --bind 0.0.0.0:8000"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
internal_port = 8000
protocol = "http"
healthcheck_enabled = true

[service.commands]
[service.commands.release]
command = "python manage.py migrate"

[service.vars]
DJANGO_SETTINGS_MODULE = "learnmore_plus.settings.prod"
SECRET_KEY = "railway-deployment-secret-key-placeholder-change-in-dashboard"
DEBUG = "False"
PYTHONUNBUFFERED = "1"
ALLOWED_HOSTS = ".railway.app,localhost,127.0.0.1"

# Database and Redis services
[[database]]
plan = "shared"
name = "postgres"

[[redis]]
plan = "starter"
name = "cache"