# Railway configuration for Docker-based Django deployment

[service]
internal_port = 8000
protocol = "http"
healthcheck_enabled = true

[service.healthcheck]
path = "/health/"
interval = 30
timeout = 10
retries = 3