[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn learnmore.wsgi:application"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.11" 