# Railway configuration for Python/Django deployment
[build]
builder = "RAILPACK"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn learnmore.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 8 --timeout 0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 