# Railway configuration for Python/Django deployment
[build]
builder = "DOCKERFILE"
dockerfilePath = "djangoapps/learnmore-reborn/Dockerfile"

[deploy]
startCommand = "/app/entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 