# Railway configuration for Python/Django deployment
[build]
builder = "RAILPACK"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn learnmore.wsgi:application --bind 0.0.0.0:8080 --workers 2 --threads 8 --timeout 0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 