# Generated by Django 5.2 on 2025-05-20 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('student_id', models.CharField(blank=True, help_text='Student ID number if applicable', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or faculty', max_length=100)),
                ('is_instructor', models.BooleanField(default=False, help_text='Whether this user can create and manage courses')),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth ID if user signs in with Google', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
