# Generated by Django 5.2.1 on 2025-05-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_completion_criteria_module_content_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress Records'},
        ),
        migrations.AddField(
            model_name='progress',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='progress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent on course in seconds'),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this module in seconds')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_position', models.JSONField(default=dict, help_text='Stores position in module content (e.g. video timestamp)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.module')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='progress.progress')),
            ],
            options={
                'verbose_name_plural': 'Module Progress',
                'unique_together': {('progress', 'module')},
            },
        ),
    ]
